# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7k325tfbg676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/darshana/newlowrisc/lowrisc-chip/fpga/board/sasebo/ip_repo/edit_myip_v1_1.cache/wt [current_project]
set_property parent.project_path /home/darshana/newlowrisc/lowrisc-chip/fpga/board/sasebo/ip_repo/edit_myip_v1_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/darshana/newlowrisc/lowrisc-chip/fpga/board/sasebo/ip_repo/myip_1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/darshana/newlowrisc/lowrisc-chip/fpga/board/sasebo/ip_repo/myip_1.1/hdl/myip_v1_1_S00_AXI.v
  /home/darshana/newlowrisc/lowrisc-chip/fpga/board/sasebo/ip_repo/myip_1.1/hdl/myip_v1_1.v
}
synth_design -top myip_v1_1 -part xc7k325tfbg676-1
write_checkpoint -noxdef myip_v1_1.dcp
catch { report_utilization -file myip_v1_1_utilization_synth.rpt -pb myip_v1_1_utilization_synth.pb }
